<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

      <Authors>SynesthesiaDev_</Authors>
      <Description>🌙 Lightweight and easy-to-use local databse for C# </Description>
      <RepositoryUrl>https://github.com/SynesthesiaDev/Nocturne</RepositoryUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <IsPackable>true</IsPackable>
      <PackageId>SynesthesiaDev.Nocturne.Database</PackageId>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Faster.Map" Version="8.1.1" />
      <PackageReference Include="Serilog" Version="4.4.0-dev-02437" />
      <PackageReference Include="Serilog.Sinks.TextWriter" Version="3.0.0" />
      <PackageReference Include="SynesthesiaDev.Codon.BinaryCodec" Version="2026.623.0" />
      <PackageReference Include="SynesthesiaUtils" Version="2026.614.0" />
    </ItemGroup>

</Project>
